general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = ~/.config/hypr/wallpaper.png   # o usa tu wallpaper
    blur_passes = 2
    blur_size = 6
    noise = 0.02
}

# reloj
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(eeeeeeff)
    font_size = 80
    position = 0, 120
    halign = center
    valign = center
}

# fecha
label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"
    color = rgba(aaaaaaff)
    font_size = 18
    position = 0, 60
    halign = center
    valign = center
}

# input de contraseña
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2

    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(444444ff)
    inner_color = rgba(000000aa)
    font_color = rgba(ffffffaa)

    fade_on_empty = false

    placeholder_text = <span foreground="##aaaaaa">Ingrese contraseña</span>

    position = 0, -50
    halign = center
    valign = center
}
