general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

#bloqueo a los 30 min
listener {
    timeout = 1800
    on-timeout = hyprlock
}

#apagar pantalla a los 35 min (opcional)
listener {
    timeout = 2100
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
