# 🐱 Fuente
font_family      JetBrainsMono Nerd Font
font_size        13.0
disable_ligatures never
allow_remote_control yes

# ✏️ Cursor
cursor_shape     beam
cursor_blink_interval 0.5

# 📐 Layout
window_padding_width 10
window_margin_width  6
placement_strategy   center
remember_window_size no

# 🧭 Ventana
hide_window_decorations yes
confirm_os_window_close 0

# 🎨 Transparencia (balanceada)
background_opacity 0.90
dynamic_background_opacity yes

# ✨ Scroll & selección
scrollback_lines 10000
copy_on_select yes
strip_trailing_spaces smart

# 🔇 Sonido
enable_audio_bell no

# 🧩 Tabs
tab_bar_style powerline
tab_bar_edge bottom
tab_powerline_style slanted



include colors.conf

