[config]
reload_apps = false
fallback_color = "#89b4fa"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/style.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.eww]
input_path = "~/.config/matugen/templates/eww.scss"
output_path = "~/.config/eww/eww.scss"

[templates.hyprland-colors]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/modules/colors.conf"
post_hook = "hyprctl reload"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "pkill -SIGUSR1 kitty"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk.css"
output_path = "~/.config/gtk-3.0/gtk.css"
post_hook = "gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark' && gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.wlogout]
input_path = "~/.config/matugen/templates/wlogout.css"
output_path = "~/.config/wlogout/colors.css"
post_hook = "python3 ~/.config/wlogout/colorize.py"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync.css"
output_path = "~/.config/swaync/style.css"
post_hook = "pkill swaync; sleep 0.3; swaync &"
