#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox


exec-once = awww-daemon
# exec-once = ~/.config/hypr/scripts/wallpaper-daemon.sh
exec-once = swaync
exec-once = hypridle
exec-once = waybar
exec-once = eww daemon
exec-once = bash -c 'sleep 1 && systemd-run --user --no-block bash ~/.config/eww/scripts/music-monitor.sh'
# exec-once = ~/.config/hypr/scripts/start-gapless.sh
exec-once = wl-paste --watch --type text/plain cliphist -max-items 7 store
