##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# G4Music: iniciar en special workspace sin mostrarse en pantalla
windowrule {
    name = g4music-silent-start
    match:class = ^(com\.github\.neithern\.g4music)$

    workspace = special:g4music silent
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Monitor laptop
workspace = 1, monitor:eDP-2, persistent:true
workspace = 2, monitor:eDP-2, persistent:true
workspace = 3, monitor:eDP-2, persistent:true
workspace = 4, monitor:eDP-2, persistent:true
workspace = 5, monitor:eDP-2, persistent:true
workspace = 6, monitor:eDP-2, persistent:true
workspace = 7, monitor:eDP-2, persistent:true
workspace = 8, monitor:eDP-2, persistent:true
workspace = 9, monitor:eDP-2, persistent:true

# Waydroid
windowrule {
    name = waydroid-float
    match:class = ^(Waydroid)$

    float = yes
    size = 412 892
    center = yes
}

# Monitor HDMI
workspace = 10, monitor:HDMI-A-1, persistent:true
workspace = 11, monitor:HDMI-A-1, persistent:true
workspace = 12, monitor:HDMI-A-1, persistent:true
workspace = 13, monitor:HDMI-A-1, persistent:true
workspace = 14, monitor:HDMI-A-1, persistent:true
workspace = 15, monitor:HDMI-A-1, persistent:true
workspace = 16, monitor:HDMI-A-1, persistent:true
workspace = 17, monitor:HDMI-A-1, persistent:true
workspace = 18, monitor:HDMI-A-1, persistent:true
